name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: npm ci && npm run build
      - name: Zip
        run: tar -czvf build.tar.gz build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build.tar.gz
